# Generated by Django 5.2.6 on 2025-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('best_time_to_call', models.CharField(max_length=20)),
                ('town_city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('how_did_you_hear_about_us', models.CharField(blank=True, help_text='Optional: Let us know how you found us', max_length=255, null=True)),
                ('message_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('care_for', models.CharField(choices=[('self', 'For Myself'), ('loved_one', 'For a Loved One')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
