# Generated by Django 5.2.6 on 2025-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('role_applied_for', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('has_experience', models.BooleanField(default=False)),
                ('experience_summary', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, help_text='E.g., First Aid, NVQ', null=True)),
                ('availability', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('weekends', 'Weekends'), ('overnights', 'Overnights'), ('live_in', 'Live-in care')], max_length=20, null=True)),
                ('eligible_to_work', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('cv_resume', models.FileField(upload_to='applications/cv/')),
                ('consent_given', models.BooleanField(default=False, help_text='Applicant agreed to processing of their data for recruitment purposes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
