# Generated by Django 5.2.6 on 2025-10-01 11:35

import blog.utils
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=265, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload a thumbnail image for this article (recommended: 1200x630px)', max_length=500, null=True, upload_to=blog.utils.article_thumbnail_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_publish', 'Can publish articles')],
                'indexes': [models.Index(fields=['-created_at'], name='blog_articl_created_d4ff1b_idx'), models.Index(fields=['published'], name='blog_articl_publish_2d0d49_idx')],
            },
        ),
    ]
