# Generated by Django 5.2.6 on 2025-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('consultation_for', models.CharField(choices=[('self', 'Myself'), ('family', 'Family Care'), ('client', 'Client')], max_length=20)),
                ('type_of_care', models.CharField(blank=True, help_text='Optional, if known', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of needs or questions', null=True)),
                ('preferred_datetime', models.DateTimeField(blank=True, help_text='Preferred consultation date & time', null=True)),
                ('how_did_you_hear', models.CharField(blank=True, choices=[('google', 'Google Search'), ('social_media', 'Social Media'), ('friend', 'Friend / Word of Mouth'), ('advertisement', 'Advertisement'), ('other', 'Other')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
